apiVersion: v1
kind: Service
metadata:
  name: mqtt-service
    #annotations:           # <-- Which IP pool to use
    #metallb.universe.tf/address-pool: lb-static-ips
spec:
  selector:
    app: mqtt
  type: LoadBalancer
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      nodePort: 31736
