apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-deployment
    #namespace: mosquitto
  labels:
    app: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
      - name: mqtt
        image: eclipse-mosquitto
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1883
        volumeMounts:
        - name: mqtt-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
      volumes:
        - name: mqtt-config
          configMap:
            name: mqtt-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-configmap
    #namespace: mosquitto
data:
  mosquitto.conf: |-
    listener 1883
    allow_anonymous true
---
