apiVersion: v1
kind: Service
metadata:
  name: webapp-service
    #annotations:           # <-- Which IP pool to use
    #metallb.universe.tf/address-pool: lb-static-ips
spec:
  selector:
    app: webapp
  type: LoadBalancer
  ports:
    - name: webapp
      port: 8080
      targetPort: 8080
        #nodePort: 30005
